---
version: '3'
services:

  db:
    hostname: db
    container_name: db
    image: postgres:13
    ports:
      - '5433:5432'
    volumes:
      - ./data/:/docker-entrypoint-initdb.d/
      # - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
    tty: true
    restart: unless-stopped
  
